name: My First CI

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать мой код
        uses: actions/checkout@v4

      - name: Поздороваться
        run: echo "Привет, CI работает!"

      - name: Показать, что в папке
        run: ls -la

      - name: Собрать Docker-образ
        run: docker compose build
